# Generated by Django 4.1.5 on 2023-03-18 21:28

import FeedApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('subtitle', models.CharField(max_length=35)),
                ('description', models.TextField(max_length=255)),
                ('id_img', models.ImageField(blank=True, max_length=255, null=True, upload_to=FeedApp.models.path_and_rename)),
            ],
        ),
    ]
