# Generated by Django 4.1.5 on 2023-03-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_alter_chat_user_1_alter_chat_user_2_and_more'),
        ('UserApp', '0001_initial'),
        ('FeedApp', '0002_alter_post_id_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
