# Generated by Django 4.1.5 on 2023-04-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_msg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_msg', to='ChatApp.message'),
        ),
    ]
